name: df_safer_dart_lints_example
homepage: https://dev-cetera.com/
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.buymeacoffee.com/dev_cetera


environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  df_safer_dart_annotations:
  df_safer_dart:
dev_dependencies:
  lints: ^6.0.0
  df_safer_dart_lints:
    path: ../
