##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_safer_dart_lints
homepage: https://dev-cetera.com/
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.buymeacoffee.com/dev_cetera
description: Lints for the df_safer_dart package. Uses annotations from the df_safer_dart_annotation package.
version: 0.3.5

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  analyzer: ^7.4.5
  custom_lint_builder: ^0.7.5
  df_safer_dart_annotations: ^0.2.0
  df_safer_dart: ^0.17.3

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0


